-- AUTO-GENERATED oleh scripts/generate-seed.mjs — JANGAN edit manual.
-- Sumber: data/*.json (Kepkonsil HK.01.02/KKI/1318/2026)
-- Kurikulum program #1 (onkogin). Idempoten: aman dijalankan ulang.
-- Prasyarat: migrasi 0023 (tabel programs + kolom program_id) sudah dijalankan.

begin;

-- Tabel 10: penyakit
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 1, 'Kanker vulva', 'Malignant neoplasm of vulva', 'C51.*', '2C70.*', 'kanker') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 2, 'Kanker vagina', 'Malignant neoplasm of vagina', 'C52', '2C71.*', 'kanker') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 3, 'Kanker serviks uteri', 'Malignant neoplasm of cervix uteri', 'C53.*', '2C77.*', 'kanker') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 4, 'Kanker endometrium', 'Malignant neoplasm of endometrium', 'C54.1', '2C76.*', 'kanker') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 5, 'Leiomiosarkoma uteri', 'Uterine leiomyosarcoma', 'C54.2 ; C54.9', '2B58.1', 'sarkoma') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 6, 'Sarkoma stroma endometrium', 'Endometrial stromal sarcoma', 'C54.1', '2B5C', 'sarkoma') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 7, 'Rabdomiosarkoma (organ genital perempuan)', 'Rhabdomyosarcoma (female genital organs)', 'C55', '2B55.*', 'sarkoma') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 8, 'Adenosarkoma korpus uteri', 'Adenosarcoma of corpus uteri', 'C54.9', '2B5D.1', 'sarkoma') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 9, 'Karsinosarkoma uteri', 'Carcinosarcoma of uterus', 'C54.9', '2C76.43', 'kanker') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 10, 'Kanker tuba falopi', 'Malignant neoplasm of Fallopian tube', 'C57.0', '2C74.*', 'kanker') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 11, 'Kanker ovarium', 'Malignant neoplasm of ovary', 'C56', '2C73.*', 'kanker') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 12, 'Penyakit trofoblastik maligna', 'Gestational trophoblastic neoplasia', 'C58', '2C75.0', 'trofoblastik') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 13, 'Koriokarsinoma', 'Choriocarcinoma', 'C58', '2C75.0', 'trofoblastik') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 14, 'Mola hidatidosa dengan komplikasi', 'Hydatidiform mole with complication', 'O01.* ; D39.2', 'JA02.*', 'trofoblastik') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 15, 'Lesi intraepitel skuamosa derajat rendah vulva (VIN I)', 'LSIL of vulva (VIN I)', 'N90.0', 'GA13.1', 'pra-kanker') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 16, 'Karsinoma in situ vulva (HSIL / VIN II-III)', 'Carcinoma in situ of vulva (HSIL; VIN III)', 'D07.1', '2E67.1', 'pra-kanker') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 17, 'Lesi intraepitel skuamosa derajat rendah vagina (VaIN I)', 'LSIL of vagina (VaIN I)', 'N89.0', 'GA14.6', 'pra-kanker') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 18, 'Karsinoma in situ vagina (HSIL / VaIN II-III)', 'Carcinoma in situ of vagina (HSIL; VaIN III)', 'D07.2', '2E67.22', 'pra-kanker') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 19, 'Lesi intraepitel skuamosa derajat rendah serviks (CIN I)', 'LSIL of cervix (CIN I)', 'N87.0', 'GA15.7', 'pra-kanker') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 20, 'Lesi intraepitel skuamosa derajat tinggi serviks (HSIL / CIN II-III)', 'HSIL of cervix (CIS; CIN II-III)', 'D06.*', '2E66.2', 'pra-kanker') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 21, 'Hiperplasia endometrium atipik', 'Endometrial hyperplasia, atypical', 'N85.1', 'GA16.0', 'pra-kanker') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 22, 'Karsinoma in situ endometrium', 'Carcinoma in situ of endometrium', 'D07.0', '2E67.0', 'pra-kanker') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 23, 'Plasenta previa dengan kecurigaan akreta', 'Placenta praevia with suspected placenta accreta', 'O43.2 ; O44.* ; O72.*', 'JA8A.2', 'obstetri-onkologi') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 24, 'Skrining kanker payudara', 'Screening for malignant neoplasm of breast', 'Z12.3', 'QA09.3', 'skrining') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 25, 'Tumor epitel borderline ovarium', 'Borderline epithelial tumour of ovary', 'D39.1', '2F76', 'borderline') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 26, 'Ruptur uteri dengan penyulit lainnya', 'Uterine rupture with complication', 'O71.1 ; O72.*', 'JB0A.0 ; JB0A.1', 'obstetri-onkologi') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;
insert into diseases (program_id, no, nama_id, nama_en, icd10, icd11, kelompok) values ((select id from programs where kode='onkogin'), 27, 'Leiomioma uteri dengan penyulit lainnya', 'Uterine leiomyoma with complication', 'D25.*', '2E86.0', 'jinak-kompleks') on conflict (program_id, no) do update set nama_id=excluded.nama_id, nama_en=excluded.nama_en, icd10=excluded.icd10, icd11=excluded.icd11, kelompok=excluded.kelompok;

-- Tabel 18: kompetensi penatalaksanaan
insert into clinical_competencies (program_id, kode, no, komponen, penjabaran, kriteria_kinerja, target_min, satuan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PK-01', 1, 'Anamnesis', 'Anamnesis onkologi komprehensif: gejala konstitusional/organ-spesifik, ECOG, riwayat herediter (BRCA/Lynch), toksisitas terapi, isu fertilitas/kontrasepsi, nyeri-nutrisi-psikososial, red flags; informed consent singkat; ringkasan masalah.', 'Kelengkapan data kunci; identifikasi red flags; ECOG terdokumentasi.', 120, 'encounter anamnesis onkologi mandiri', false) on conflict (program_id, kode) do update set komponen=excluded.komponen, penjabaran=excluded.penjabaran, kriteria_kinerja=excluded.kriteria_kinerja, target_min=excluded.target_min, satuan=excluded.satuan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into clinical_competencies (program_id, kode, no, komponen, penjabaran, kriteria_kinerja, target_min, satuan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PK-02', 2, 'Pemeriksaan Fisik', 'Pemeriksaan umum & onkologi ginekologi (termasuk nodal basin, rektovaginal/EUA bila indikasi) dengan pendamping; aseptik; keselamatan/kenyamanan; dokumentasi.', 'Teknik benar & aman; temuan kunci (nodal/organ infiltration) teridentifikasi; dokumentasi lengkap.', 120, 'pemeriksaan fisik onkologi komprehensif', false) on conflict (program_id, kode) do update set komponen=excluded.komponen, penjabaran=excluded.penjabaran, kriteria_kinerja=excluded.kriteria_kinerja, target_min=excluded.target_min, satuan=excluded.satuan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into clinical_competencies (program_id, kode, no, komponen, penjabaran, kriteria_kinerja, target_min, satuan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PK-03', 3, 'Penentuan Kebutuhan Pemeriksaan Penunjang', 'Seleksi laboratorium, imaging (USG/CT/MRI/PET-CT), penanda tumor, histopatologi/IHC, biomarker (ER/PR, p16, p53, HER2, MMR/MSI, BRCA/HRD, PD-L1); prioritisasi biaya-manfaat; permintaan terstandar.', 'Ketepatan indikasi/prioritas; pemeriksaan tidak perlu minimal; pemesanan tepat waktu.', 80, 'keputusan paket work-up onkologi', false) on conflict (program_id, kode) do update set komponen=excluded.komponen, penjabaran=excluded.penjabaran, kriteria_kinerja=excluded.kriteria_kinerja, target_min=excluded.target_min, satuan=excluded.satuan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into clinical_competencies (program_id, kode, no, komponen, penjabaran, kriteria_kinerja, target_min, satuan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PK-04', 4, 'Interpretasi Hasil Pemeriksaan', 'Integrasi radiologi-patologi-biomarker; penetapan FIGO sementara; baseline RECIST; rekomendasi tindak lanjut.', 'Akurasi interpretasi; konsistensi staging klinis; rekomendasi tindak lanjut tepat.', 80, 'interpretasi terintegrasi', false) on conflict (program_id, kode) do update set komponen=excluded.komponen, penjabaran=excluded.penjabaran, kriteria_kinerja=excluded.kriteria_kinerja, target_min=excluded.target_min, satuan=excluded.satuan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into clinical_competencies (program_id, kode, no, komponen, penjabaran, kriteria_kinerja, target_min, satuan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PK-05', 5, 'Penetapan Diagnosis Kerja dan Banding', 'Problem list; primer vs metastasis/unknown primary/sinkron; pengelompokan risiko; penetapan FIGO; rasionalisasi banding.', 'Akurasi diagnosis kerja; daftar banding relevan; penetapan FIGO konsisten.', 80, 'penetapan diagnosis/staging', false) on conflict (program_id, kode) do update set komponen=excluded.komponen, penjabaran=excluded.penjabaran, kriteria_kinerja=excluded.kriteria_kinerja, target_min=excluded.target_min, satuan=excluded.satuan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into clinical_competencies (program_id, kode, no, komponen, penjabaran, kriteria_kinerja, target_min, satuan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PK-06', 6, 'Perencanaan Terapi (Farmakologis/Nonfarmakologis)', 'Rencana multimodal berbasis NCCN/ESGO/FIGO: urutan operasi-CT-RT/targeted-imuno/hormonal; fertility-sparing bila layak; pencegahan VTE/antiemetik; informed consent; koordinasi MDT.', 'Adherence guideline; kesalahan dosis/kontraindikasi minimal.', 50, 'rencana terapi individual', false) on conflict (program_id, kode) do update set komponen=excluded.komponen, penjabaran=excluded.penjabaran, kriteria_kinerja=excluded.kriteria_kinerja, target_min=excluded.target_min, satuan=excluded.satuan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into clinical_competencies (program_id, kode, no, komponen, penjabaran, kriteria_kinerja, target_min, satuan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PK-07', 7, 'Evaluasi Respon dan Penyesuaian Terapi', 'Penilaian respons RECIST; penilaian toksisitas; modifikasi dosis/jadwal; supportive care.', 'Klasifikasi RECIST tepat; penanganan toksisitas sesuai protokol; tindak lanjut tepat waktu.', 50, 'evaluasi respons/toksisitas', false) on conflict (program_id, kode) do update set komponen=excluded.komponen, penjabaran=excluded.penjabaran, kriteria_kinerja=excluded.kriteria_kinerja, target_min=excluded.target_min, satuan=excluded.satuan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into clinical_competencies (program_id, kode, no, komponen, penjabaran, kriteria_kinerja, target_min, satuan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PK-08', 8, 'Penetapan Prognosis', 'Faktor prognostik (stadium, grade, LVSI, nodal, biomarker/genetik); kelompok risiko; survivorship plan; indikasi paliatif.', 'Estimasi risiko konsisten dengan bukti; komunikasi prognosis jelas; rencana kontrol terdokumentasi.', 20, 'diskusi prognosis & rencana kontrol', false) on conflict (program_id, kode) do update set komponen=excluded.komponen, penjabaran=excluded.penjabaran, kriteria_kinerja=excluded.kriteria_kinerja, target_min=excluded.target_min, satuan=excluded.satuan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into clinical_competencies (program_id, kode, no, komponen, penjabaran, kriteria_kinerja, target_min, satuan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PK-09', 9, 'Dokumentasi Medis dan Komunikasi Hasil', 'Rekam medis onkologi terstruktur (SOAP, staging, biomarker); ringkasan klinis; MDT tumor board; rujukan genetic counseling; breaking bad news; handover (SBAR).', 'Kelengkapan dokumentasi; presentasi MDT efektif; komunikasi hasil tepat waktu.', 150, 'entri/handover terverifikasi', false) on conflict (program_id, kode) do update set komponen=excluded.komponen, penjabaran=excluded.penjabaran, kriteria_kinerja=excluded.kriteria_kinerja, target_min=excluded.target_min, satuan=excluded.satuan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into clinical_competency_subtargets (program_id, competency_id, nama, kode, target_min) select (select id from programs where kode='onkogin'), id, 'Presentasi MDT', 'mdt', 20 from clinical_competencies where kode='PK-09' and program_id=(select id from programs where kode='onkogin') and not exists (select 1 from clinical_competency_subtargets st join clinical_competencies cc on cc.id=st.competency_id where cc.kode='PK-09' and cc.program_id=(select id from programs where kode='onkogin') and st.nama='Presentasi MDT');
insert into clinical_competency_subtargets (program_id, competency_id, nama, kode, target_min) select (select id from programs where kode='onkogin'), id, 'Breaking bad news', 'breaking_bad_news', 10 from clinical_competencies where kode='PK-09' and program_id=(select id from programs where kode='onkogin') and not exists (select 1 from clinical_competency_subtargets st join clinical_competencies cc on cc.id=st.competency_id where cc.kode='PK-09' and cc.program_id=(select id from programs where kode='onkogin') and st.nama='Breaking bad news');

-- Tabel 24: prosedur
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-01', 1, 'Diagnosis dan manajemen kanker ginekologi', 100, 'kasus baru', 'penanggung jawab utama', 'dengan verifikasi MDT', false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-02', 2, 'Ultrasonografi ginekologi onkologi (TA/TV, IOTA/ADNEX, Doppler)', 30, 'pemeriksaan + laporan', 'mandiri', 'Diverifikasi terhadap PDF asli: target ≥30.', false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-03', 3, 'Seksio sesarea pada kecurigaan plasenta akreta (PAS) dengan penyulit', 3, 'kasus PAS (SC ± histerektomi)', 'operator utama / ko-operator senior', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-04', 4, 'Ligasi arteri uterina asendens dengan penyulit', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-05', 5, 'Ligasi arteri hipogastrika (iliaka interna) dengan penyulit', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-06', 6, 'Histerektomi abdominal dengan penyulit', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-07', 7, 'Salpingo-ooforektomi dengan penyulit', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-08', 8, 'Kistektomi dengan penyulit', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-09', 9, 'Miomektomi dengan penyulit', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-10', 10, 'Reseksi adenomiosis dengan penyulit', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-11', 11, 'Adesiolisis tajam dengan penyulit', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-12', 12, 'Destruksi lesi kondiloma di luar vulva pada organ reproduksi', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-13', 13, 'Sistoskopi dan/atau proktoskopi', 3, 'prosedur', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-14', 14, 'Biopsi kelenjar getah bening superfisial', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-15', 15, 'Aspirasi Jarum Halus (FNAB) dan biopsi trucut', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-16', 16, 'Kolposkopi dengan/tanpa biopsi (vulva/vagina/serviks)', 3, 'prosedur', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-17', 17, 'Eksisi/biopsi pada lesi vulva/vagina/serviks', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-18', 18, 'Eksisi tumor pada vulva/vagina (radikal, wide local excision)', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-19', 19, 'Vulvektomi sederhana/radikal', 2, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-20', 20, 'Vaginektomi parsial/total/radikal', 2, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-21', 21, 'Bedah rekonstruksi abdomen bawah dan regio genitalia', 2, 'rekonstruksi kompleks', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-22', 22, 'Diseksi/sampling KGB inguinofemoral (unilateral/bilateral)', 2, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-23', 23, 'Polipektomi serviks', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-24', 24, 'Konisasi (CKC/LEEP/LEETZ/krioterapi)', 3, 'tindakan (bervariasi teknik)', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-25', 25, 'Biopsi aspirasi endometrium', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-26', 26, 'Histeroskopi diagnostik/operatif dengan/tanpa penyulit', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-27', 27, 'Histerektomi sederhana/tipe I (laparotomi/laparoskopi)', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-28', 28, 'Salpingektomi dan/atau ooforektomi (uni/bilateral; laparotomi/laparoskopi)', 3, 'prosedur (bervariasi akses & sisi)', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-29', 29, 'Kistektomi (uni/bilateral; laparotomi/laparoskopi)', 3, 'kistektomi kompleks', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-30', 30, 'Diseksi/sampling KGB pelvis dan/atau para-aorta (laparotomi/laparoskopi)', 3, 'prosedur', 'operator', '≥2 melibatkan para-aorta', false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-31', 31, 'Omentektomi infrakolik/suprakolik (laparotomi/laparoskopi)', 3, 'tindakan (bervariasi akses & tingkat)', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-32', 32, 'Biopsi peritoneum/eksisi lesi peritoneum', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-33', 33, 'Appendektomi (dalam konteks onkologi)', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-34', 34, 'Surgical staging kanker ginekologi (ovarium/tuba/endometrium/serviks/vagina/vulva)', 3, 'staging kanker ovarium', 'operator', 'termasuk ≥2 fertility-sparing bila tersedia', false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-35', 35, 'Biopsi/debulking massa tumor ginekologi (laparotomi/laparoskopi)', 3, 'prosedur (beragam akses)', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-36', 36, 'Operasi ultra-radikal (peritonektomi, stripping diafragma, reseksi usus, reseksi hati parsial, splenektomi, HIPEC)', 2, 'operasi multiperan', 'operator/ko-operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-37', 37, 'Reseksi usus & anastomosis dalam onkologi', 2, 'tindakan', 'operator/ko-operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-38', 38, 'Ureterolisis/rekonstruksi ureter dalam onkologi', 2, 'rekonstruksi kompleks', 'operator/ko-operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-39', 39, 'Repair vaskular dalam onkologi', 2, 'tindakan', 'operator/ko-operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-40', 40, 'Penjahitan laserasi usus atau kandung kemih', 3, 'repair', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-41', 41, 'Histerektomi radikal (tipe II/III/IV; laparotomi/laparoskopi)', 3, 'tindakan (bervariasi tipe & akses)', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-42', 42, 'Histerektomi radikal (nerve-preserving)', 3, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-43', 43, 'Trakelektomi sederhana/radikal (laparotomi/laparoskopi/vaginal)', 2, 'tindakan (bervariasi pendekatan)', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-44', 44, 'Oophoropexy (ovarian transposition)', 2, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-45', 45, 'Parametrektomi (laparotomi/laparoskopi ultraradikal)', 2, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-46', 46, 'Temporary Infrarenal Aortic Clamping (klem sementara aorta abdominalis)', 2, 'tindakan', 'operator/ko-operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-47', 47, 'Prosedur LEER (Laterally Extended Endopelvic Resection)', 2, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-48', 48, 'Eksenterasi pelvis (anterior/posterior/total)', 2, 'tindakan', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-49', 49, 'Operasi ginekologi dengan Robotic Surgery (MIS robotik)', 2, 'kasus robotik', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-50', 50, 'Sentinel Lymph Node (SLN) mapping & biopsi pada kanker ginekologi', 2, 'prosedur', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-51', 51, 'Histerektomi vaginal (sederhana/radikal, ±SO, ±kolporafi)', 2, 'tindakan (variasi kompleksitas)', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-52', 52, 'Panikulektomi', 2, 'tindakan', 'operator atau ko-operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-53', 53, 'Kemoterapi, imunoterapi, terapi hormonal, terapi target', 3, 'siklus terapi sistemik (beragam modalitas)', 'penanggung jawab', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-54', 54, 'Penggunaan chemoport & pemberian kemoterapi', 2, 'sesi infus via port (akses/perawatan/pemberian)', 'operator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-55', 55, 'Koordinasi radioterapi pada kanker ginekologi', 3, 'paket RT (EBRT/brachy/konkomitan) hingga selesai', 'koordinator', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-56', 56, 'Terapi paliatif nyeri pada keganasan ginekologi dengan penyulit', 3, 'episode manajemen nyeri kompleks', 'penanggung jawab', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;
insert into procedures (program_id, kode, no, nama, target_min, satuan, peran_disyaratkan, syarat_tambahan, perlu_verifikasi) values ((select id from programs where kode='onkogin'), 'PR-57', 57, 'Terapi paliatif nutrisi pada keganasan ginekologi dengan penyulit', 3, 'rencana nutrisi paliatif kompleks', 'penanggung jawab', null, false) on conflict (program_id, kode) do update set nama=excluded.nama, target_min=excluded.target_min, satuan=excluded.satuan, peran_disyaratkan=excluded.peran_disyaratkan, syarat_tambahan=excluded.syarat_tambahan, perlu_verifikasi=excluded.perlu_verifikasi;

-- Tabel 30: pengetahuan penatalaksanaan
insert into knowledge_items (program_id, kode, topik, kategori, osce_min, mcq_min) values ((select id from programs where kode='onkogin'), 'KP-01', 'Anamnesis ginekologi-onkologi terstruktur', 'penatalaksanaan', 70, 70) on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, osce_min, mcq_min) values ((select id from programs where kode='onkogin'), 'KP-02', 'Pemeriksaan fisik ginekologi-onkologi', 'penatalaksanaan', 70, 70) on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, osce_min, mcq_min) values ((select id from programs where kode='onkogin'), 'KP-03', 'Pemilihan pemeriksaan penunjang (IHC/biomarker, CT/MRI/PET)', 'penatalaksanaan', 70, 70) on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, osce_min, mcq_min) values ((select id from programs where kode='onkogin'), 'KP-04', 'Interpretasi hasil pemeriksaan & baseline RECIST', 'penatalaksanaan', 70, 70) on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, osce_min, mcq_min) values ((select id from programs where kode='onkogin'), 'KP-05', 'Penetapan diagnosis kerja & banding (FIGO)', 'penatalaksanaan', 70, 70) on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, osce_min, mcq_min) values ((select id from programs where kode='onkogin'), 'KP-06', 'Perencanaan terapi (NCCN/ESGO/FIGO)', 'penatalaksanaan', 70, 70) on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, osce_min, mcq_min) values ((select id from programs where kode='onkogin'), 'KP-07', 'Evaluasi respon & penyesuaian terapi', 'penatalaksanaan', 70, 70) on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, osce_min, mcq_min) values ((select id from programs where kode='onkogin'), 'KP-08', 'Penetapan prognosis & survivorship', 'penatalaksanaan', 70, 70) on conflict (program_id, kode) do update set topik=excluded.topik;

-- Tabel 36: pengetahuan prosedur (di-generate dari procedures)
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-01', 'Pengetahuan: Diagnosis dan manajemen kanker ginekologi', 'prosedur', id, 70, 70 from procedures where kode='PR-01' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-02', 'Pengetahuan: Ultrasonografi ginekologi onkologi (TA/TV, IOTA/ADNEX, Doppler)', 'prosedur', id, 70, 70 from procedures where kode='PR-02' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-03', 'Pengetahuan: Seksio sesarea pada kecurigaan plasenta akreta (PAS) dengan penyulit', 'prosedur', id, 70, 70 from procedures where kode='PR-03' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-04', 'Pengetahuan: Ligasi arteri uterina asendens dengan penyulit', 'prosedur', id, 70, 70 from procedures where kode='PR-04' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-05', 'Pengetahuan: Ligasi arteri hipogastrika (iliaka interna) dengan penyulit', 'prosedur', id, 70, 70 from procedures where kode='PR-05' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-06', 'Pengetahuan: Histerektomi abdominal dengan penyulit', 'prosedur', id, 70, 70 from procedures where kode='PR-06' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-07', 'Pengetahuan: Salpingo-ooforektomi dengan penyulit', 'prosedur', id, 70, 70 from procedures where kode='PR-07' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-08', 'Pengetahuan: Kistektomi dengan penyulit', 'prosedur', id, 70, 70 from procedures where kode='PR-08' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-09', 'Pengetahuan: Miomektomi dengan penyulit', 'prosedur', id, 70, 70 from procedures where kode='PR-09' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-10', 'Pengetahuan: Reseksi adenomiosis dengan penyulit', 'prosedur', id, 70, 70 from procedures where kode='PR-10' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-11', 'Pengetahuan: Adesiolisis tajam dengan penyulit', 'prosedur', id, 70, 70 from procedures where kode='PR-11' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-12', 'Pengetahuan: Destruksi lesi kondiloma di luar vulva pada organ reproduksi', 'prosedur', id, 70, 70 from procedures where kode='PR-12' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-13', 'Pengetahuan: Sistoskopi dan/atau proktoskopi', 'prosedur', id, 70, 70 from procedures where kode='PR-13' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-14', 'Pengetahuan: Biopsi kelenjar getah bening superfisial', 'prosedur', id, 70, 70 from procedures where kode='PR-14' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-15', 'Pengetahuan: Aspirasi Jarum Halus (FNAB) dan biopsi trucut', 'prosedur', id, 70, 70 from procedures where kode='PR-15' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-16', 'Pengetahuan: Kolposkopi dengan/tanpa biopsi (vulva/vagina/serviks)', 'prosedur', id, 70, 70 from procedures where kode='PR-16' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-17', 'Pengetahuan: Eksisi/biopsi pada lesi vulva/vagina/serviks', 'prosedur', id, 70, 70 from procedures where kode='PR-17' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-18', 'Pengetahuan: Eksisi tumor pada vulva/vagina (radikal, wide local excision)', 'prosedur', id, 70, 70 from procedures where kode='PR-18' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-19', 'Pengetahuan: Vulvektomi sederhana/radikal', 'prosedur', id, 70, 70 from procedures where kode='PR-19' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-20', 'Pengetahuan: Vaginektomi parsial/total/radikal', 'prosedur', id, 70, 70 from procedures where kode='PR-20' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-21', 'Pengetahuan: Bedah rekonstruksi abdomen bawah dan regio genitalia', 'prosedur', id, 70, 70 from procedures where kode='PR-21' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-22', 'Pengetahuan: Diseksi/sampling KGB inguinofemoral (unilateral/bilateral)', 'prosedur', id, 70, 70 from procedures where kode='PR-22' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-23', 'Pengetahuan: Polipektomi serviks', 'prosedur', id, 70, 70 from procedures where kode='PR-23' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-24', 'Pengetahuan: Konisasi (CKC/LEEP/LEETZ/krioterapi)', 'prosedur', id, 70, 70 from procedures where kode='PR-24' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-25', 'Pengetahuan: Biopsi aspirasi endometrium', 'prosedur', id, 70, 70 from procedures where kode='PR-25' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-26', 'Pengetahuan: Histeroskopi diagnostik/operatif dengan/tanpa penyulit', 'prosedur', id, 70, 70 from procedures where kode='PR-26' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-27', 'Pengetahuan: Histerektomi sederhana/tipe I (laparotomi/laparoskopi)', 'prosedur', id, 70, 70 from procedures where kode='PR-27' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-28', 'Pengetahuan: Salpingektomi dan/atau ooforektomi (uni/bilateral; laparotomi/laparoskopi)', 'prosedur', id, 70, 70 from procedures where kode='PR-28' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-29', 'Pengetahuan: Kistektomi (uni/bilateral; laparotomi/laparoskopi)', 'prosedur', id, 70, 70 from procedures where kode='PR-29' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-30', 'Pengetahuan: Diseksi/sampling KGB pelvis dan/atau para-aorta (laparotomi/laparoskopi)', 'prosedur', id, 70, 70 from procedures where kode='PR-30' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-31', 'Pengetahuan: Omentektomi infrakolik/suprakolik (laparotomi/laparoskopi)', 'prosedur', id, 70, 70 from procedures where kode='PR-31' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-32', 'Pengetahuan: Biopsi peritoneum/eksisi lesi peritoneum', 'prosedur', id, 70, 70 from procedures where kode='PR-32' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-33', 'Pengetahuan: Appendektomi (dalam konteks onkologi)', 'prosedur', id, 70, 70 from procedures where kode='PR-33' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-34', 'Pengetahuan: Surgical staging kanker ginekologi (ovarium/tuba/endometrium/serviks/vagina/vulva)', 'prosedur', id, 70, 70 from procedures where kode='PR-34' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-35', 'Pengetahuan: Biopsi/debulking massa tumor ginekologi (laparotomi/laparoskopi)', 'prosedur', id, 70, 70 from procedures where kode='PR-35' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-36', 'Pengetahuan: Operasi ultra-radikal (peritonektomi, stripping diafragma, reseksi usus, reseksi hati parsial, splenektomi, HIPEC)', 'prosedur', id, 70, 70 from procedures where kode='PR-36' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-37', 'Pengetahuan: Reseksi usus & anastomosis dalam onkologi', 'prosedur', id, 70, 70 from procedures where kode='PR-37' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-38', 'Pengetahuan: Ureterolisis/rekonstruksi ureter dalam onkologi', 'prosedur', id, 70, 70 from procedures where kode='PR-38' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-39', 'Pengetahuan: Repair vaskular dalam onkologi', 'prosedur', id, 70, 70 from procedures where kode='PR-39' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-40', 'Pengetahuan: Penjahitan laserasi usus atau kandung kemih', 'prosedur', id, 70, 70 from procedures where kode='PR-40' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-41', 'Pengetahuan: Histerektomi radikal (tipe II/III/IV; laparotomi/laparoskopi)', 'prosedur', id, 70, 70 from procedures where kode='PR-41' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-42', 'Pengetahuan: Histerektomi radikal (nerve-preserving)', 'prosedur', id, 70, 70 from procedures where kode='PR-42' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-43', 'Pengetahuan: Trakelektomi sederhana/radikal (laparotomi/laparoskopi/vaginal)', 'prosedur', id, 70, 70 from procedures where kode='PR-43' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-44', 'Pengetahuan: Oophoropexy (ovarian transposition)', 'prosedur', id, 70, 70 from procedures where kode='PR-44' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-45', 'Pengetahuan: Parametrektomi (laparotomi/laparoskopi ultraradikal)', 'prosedur', id, 70, 70 from procedures where kode='PR-45' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-46', 'Pengetahuan: Temporary Infrarenal Aortic Clamping (klem sementara aorta abdominalis)', 'prosedur', id, 70, 70 from procedures where kode='PR-46' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-47', 'Pengetahuan: Prosedur LEER (Laterally Extended Endopelvic Resection)', 'prosedur', id, 70, 70 from procedures where kode='PR-47' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-48', 'Pengetahuan: Eksenterasi pelvis (anterior/posterior/total)', 'prosedur', id, 70, 70 from procedures where kode='PR-48' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-49', 'Pengetahuan: Operasi ginekologi dengan Robotic Surgery (MIS robotik)', 'prosedur', id, 70, 70 from procedures where kode='PR-49' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-50', 'Pengetahuan: Sentinel Lymph Node (SLN) mapping & biopsi pada kanker ginekologi', 'prosedur', id, 70, 70 from procedures where kode='PR-50' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-51', 'Pengetahuan: Histerektomi vaginal (sederhana/radikal, ±SO, ±kolporafi)', 'prosedur', id, 70, 70 from procedures where kode='PR-51' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-52', 'Pengetahuan: Panikulektomi', 'prosedur', id, 70, 70 from procedures where kode='PR-52' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-53', 'Pengetahuan: Kemoterapi, imunoterapi, terapi hormonal, terapi target', 'prosedur', id, 70, 70 from procedures where kode='PR-53' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-54', 'Pengetahuan: Penggunaan chemoport & pemberian kemoterapi', 'prosedur', id, 70, 70 from procedures where kode='PR-54' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-55', 'Pengetahuan: Koordinasi radioterapi pada kanker ginekologi', 'prosedur', id, 70, 70 from procedures where kode='PR-55' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-56', 'Pengetahuan: Terapi paliatif nyeri pada keganasan ginekologi dengan penyulit', 'prosedur', id, 70, 70 from procedures where kode='PR-56' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;
insert into knowledge_items (program_id, kode, topik, kategori, procedure_id, osce_min, mcq_min) select (select id from programs where kode='onkogin'), 'KPR-57', 'Pengetahuan: Terapi paliatif nutrisi pada keganasan ginekologi dengan penyulit', 'prosedur', id, 70, 70 from procedures where kode='PR-57' and program_id=(select id from programs where kode='onkogin') on conflict (program_id, kode) do update set topik=excluded.topik;

-- Auto-agregasi: peran_dihitung override (prosedur non-bedah = {} hitung semua)
update procedures set peran_dihitung = '{}' where kode = 'PR-01' and program_id = (select id from programs where kode='onkogin');
update procedures set peran_dihitung = '{}' where kode = 'PR-02' and program_id = (select id from programs where kode='onkogin');
update procedures set peran_dihitung = '{}' where kode = 'PR-53' and program_id = (select id from programs where kode='onkogin');
update procedures set peran_dihitung = '{}' where kode = 'PR-54' and program_id = (select id from programs where kode='onkogin');
update procedures set peran_dihitung = '{}' where kode = 'PR-55' and program_id = (select id from programs where kode='onkogin');
update procedures set peran_dihitung = '{}' where kode = 'PR-56' and program_id = (select id from programs where kode='onkogin');
update procedures set peran_dihitung = '{}' where kode = 'PR-57' and program_id = (select id from programs where kode='onkogin');
update procedures set peran_dihitung = '{operator_utama}' where kode = 'PR-41' and program_id = (select id from programs where kode='onkogin');
update procedures set peran_dihitung = '{operator_utama}' where kode = 'PR-42' and program_id = (select id from programs where kode='onkogin');

-- Auto-agregasi: pemetaan prosedur -> kompetensi penatalaksanaan
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-01' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-01' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-01' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-02' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-01' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-03' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-01' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-04' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-01' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-05' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-01' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-06' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-01' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-08' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-01' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-09' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-02' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-03' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-02' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-04' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-53' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-06' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-53' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-07' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-55' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-06' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-55' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-07' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-56' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-08' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;
insert into procedure_clinical_map (procedure_id, clinical_competency_id) select p.id, c.id from procedures p, clinical_competencies c where p.kode='PR-57' and p.program_id=(select id from programs where kode='onkogin') and c.kode='PK-08' and c.program_id=(select id from programs where kode='onkogin') on conflict do nothing;

commit;
